# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EmailSentinel < Formula
  desc "Monitor Gmail and get instant notifications on desktop and mobile"
  homepage "https://github.com/datateamsix/email-sentinel"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/datateamsix/email-sentinel/releases/download/v1.0.0/email-sentinel_1.0.0_macOS_amd64.tar.gz"
      sha256 "95a61451b044dd6c87934888780baab91277e587c0a15789f5b57ca886b5e565"

      def install
        bin.install "email-sentinel"
        (etc/"email-sentinel").install "app-config.yaml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/datateamsix/email-sentinel/releases/download/v1.0.0/email-sentinel_1.0.0_macOS_arm64.tar.gz"
      sha256 "1e73ee8c2db7f1d317c09be938a9c98e36c4ff34d988290cfca19bb72f3d2933"

      def install
        bin.install "email-sentinel"
        (etc/"email-sentinel").install "app-config.yaml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/datateamsix/email-sentinel/releases/download/v1.0.0/email-sentinel_1.0.0_linux_amd64.tar.gz"
      sha256 "c9abebb12274a09fc91694aabb56543c15a31f027b3344086b8d61665a0a396e"
      def install
        bin.install "email-sentinel"
        (etc/"email-sentinel").install "app-config.yaml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/datateamsix/email-sentinel/releases/download/v1.0.0/email-sentinel_1.0.0_linux_arm64.tar.gz"
      sha256 "8c7cd2c74ea32d78655c989f29acd43a0ddeadc0b02d72e7e139daf88552b010"
      def install
        bin.install "email-sentinel"
        (etc/"email-sentinel").install "app-config.yaml"
      end
    end
  end

  test do
    system "#{bin}/email-sentinel", "--version"
  end
end
